// <auto-generated />
using System;
using CSnoek9141_Assignment2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSnoek9141_Assignment2.Migrations
{
    [DbContext(typeof(PartyDbContext))]
    [Migration("20221028195432_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CSnoek9141_Assignment2.Entities.Invitation", b =>
                {
                    b.Property<int>("InvitationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationID"), 1L, 1);

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InviteStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PartyID")
                        .HasColumnType("int");

                    b.HasKey("InvitationID");

                    b.HasIndex("PartyID");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            InvitationID = 1,
                            GuestEmail = "pmadziak@conestogac.on.ca",
                            GuestName = "Bob Jones",
                            InviteStatus = "RespondedYes",
                            PartyID = 1
                        },
                        new
                        {
                            InvitationID = 2,
                            GuestEmail = "peter.madziak@gmail.com",
                            GuestName = "Sally Smith",
                            InviteStatus = "InviteSent",
                            PartyID = 1
                        });
                });

            modelBuilder.Entity("CSnoek9141_Assignment2.Entities.Party", b =>
                {
                    b.Property<int>("PartyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartyID");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyID = 1,
                            Description = "New year's eve blast!",
                            EventDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Time Square, NY"
                        });
                });

            modelBuilder.Entity("CSnoek9141_Assignment2.Entities.Invitation", b =>
                {
                    b.HasOne("CSnoek9141_Assignment2.Entities.Party", "Party")
                        .WithMany("Invitations")
                        .HasForeignKey("PartyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("CSnoek9141_Assignment2.Entities.Party", b =>
                {
                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
